# Generated by Django 4.2.13 on 2024-07-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautycity_app', '0002_alter_employee_photo_alter_employee_rating_img_and_more'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beautycity_app.employee', verbose_name='Мастер'),
            preserve_default=False,
        ),
    ]
