# Generated by Django 4.2.13 on 2024-07-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_salon_alter_appointment_comment_and_more'),
        ('appointment', '0002_review_master'),
    ]

    operations = [
    ]
