# Generated by Django 4.2.13 on 2024-07-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_merge_20240726_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Статус оплаты'),
        ),
    ]
