# Generated by Django 4.2.13 on 2024-07-24 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('position', models.CharField(max_length=255, verbose_name='Специализация')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг')),
                ('rating_img', models.ImageField(blank=True, default='img/rating.svg', null=True, upload_to='img/employees', verbose_name='Изображение рейтинга')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт')),
                ('photo', models.ImageField(blank=True, default='img/masters/all.svg', null=True, upload_to='img/masters', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Цена')),
                ('duration', models.DurationField(help_text='Продолжительность услуги в формате ЧЧ:ММ:СС', verbose_name='Длительность')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/services', verbose_name='Изображение')),
                ('category', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='beautycity_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/salons', verbose_name='Изображение')),
                ('masters', models.ManyToManyField(related_name='salons', to='beautycity_app.employee', verbose_name='Мастера')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautycity_app.employee', verbose_name='Мастер')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautycity_app.salon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Расписание мастера',
                'verbose_name_plural': 'Расписания мастеров',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(to='beautycity_app.service', verbose_name='Услуги'),
        ),
    ]
