# Generated by Django 4.2.13 on 2024-07-25 12:13

import beautycity_app.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautycity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=beautycity_app.model_fields.ImageAndSvgField(blank=True, default='img/masters/all.svg', null=True, upload_to='img/masters', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rating_img',
            field=beautycity_app.model_fields.ImageAndSvgField(blank=True, default='img/rating.svg', null=True, upload_to='img/employees', verbose_name='Изображение рейтинга'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='img',
            field=beautycity_app.model_fields.ImageAndSvgField(blank=True, null=True, upload_to='img/salons', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=beautycity_app.model_fields.ImageAndSvgField(blank=True, null=True, upload_to='img/services', verbose_name='Изображение'),
        ),
    ]
