# Generated by Django 4.2.13 on 2024-07-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautycity_app', '0002_alter_employee_photo_alter_employee_rating_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='beautycity_app.employee', verbose_name='Мастер'),
        ),
    ]
